export type Language = 'en' | 'mr';

export const TRANSLATIONSObj: Record<Language, Record<string, string>> = {
  en: {
    // Portals Switcher
    console_active: "SHRIRAM JAL SYSTEM CONSOLE ACTIVE",
    customer_storefront: "🏡 Customer Storefront",
    live_admin: "⚙️ Live Admin Panel",
    blueprints: "📚 Engineering Blueprints",

    // Brand and Headings
    brand_title: "SHRIRAM JAL",
    brand_tagline: "PURE WATER, PURE LIFE",
    pune_trusted: "Why Shriram Jal is Ingali's Trusted Choice",
    pune_trusted_sub: "Every single drop is monitored and filtered through seven individual phases of precision purification protocols.",
    pune_premium_tag: "✨ Ingali's Premium Water Service • Owner: Ranjit More",
    order_now_banner: "ऑर्डर करा आता",
    order_now_banner_desc: "थंड आणि नॉर्मल पाण्याचे कॅन आता एक क्लिकवर ऑर्डर करा.",
    quick_shortcuts: "Quick Delivery Shortcuts",
    explore_catalog: "Explore Catalog",
    how_it_works: "Order Steps",
    water_can_normal_20l: "20L Normal Can",
    water_can_cold_20l: "20L Chilled Can",
    delivery_coverage: "Active Delivery Coverage Sector: Ingali & Hatkanangle Region",
    delivery_coverage_sub: "Operating fully integrated logistics networks from our central hub near Jain Basti, Ingali, serving:",
    feedback_residents: "Feedback From Local Residents",
    support_hotline: "📞 Help Hotline: +91 93073 19929 / +91 88560 45945",
    support_email: "info@shriramjal.com",
    owner_info: "Owner: Ranjit More",
    operational_office: "Operational Office",
    registered_hub: "Registered: near jain basti inagli, Hatkanangle, Kolhapur, IN",
    all_rights_reserved: "© 2024 Shriram Jal. All Rights Reserved.",

    // General navigation
    home: "Home",
    order_cans: "Products",
    subscription: "Subscription",
    about_us: "About Us",
    contact_us: "Contact Us",
    track_orders: "Track Orders",
    cart: "Cart",
    my_orders_footer: "My Orders",
    address_records_footer: "Address Records",

    // Auth screen & login / signup
    sign_in: "Login / Register",
    sign_up: "Sign Up",
    log_out: "Log Out",
    welcome: "Welcome",
    login_required: "Access Restricted",
    login_subtext: "Please sign in or create an account to place water orders and track live deliveries instantly.",
    enter_email: "Email address or username",
    enter_password: "Password",
    enter_name: "Full Name",
    enter_phone: "Phone Number",
    no_account: "Don't have an account?",
    already_member: "Already registered?",
    sign_up_cta: "Create New Account",
    sign_in_cta: "Login Securely",
    admin_restriction_title: "Administrative Terminal Locked",
    admin_restriction_sub: "Ingali administration panel requires verified supervisor access credentials. Normal users are not permitted here.",
    admin_login_cta: "Authenticate Admin User",
    authenticated_as: "Authenticated as",
    logged_in_as: "Logged in as",

    // Catalog & filter
    product_catalog: "Refreshing Products Catalog",
    all_types: "All Temperatures",
    normal_temp: "Normal Cans",
    cold_temp: "Chilled Cans",
    all_sizes: "All Capacity Sizes",
    select_size: "Select Size",
    available_stock: "In Stock",
    out_of_stock: "Out of Stock",
    add_to_cart: "Add To Cart",
    buy_now: "Order Instantly",
    quantity: "Quantity",
    fast_delivery: "⚡ Delivered in 3 hours",

    // Cart and order checkout
    cart_summary: "Your Cart Items Selection",
    cart_empty: "Your water cart is completely empty.",
    cart_empty_sub: "Browse our double-sealed premium normal and chilled water cans to proceed with booking.",
    start_shopping: "Browse Water Products",
    checkout_process: "Secure Checkout Pipeline",
    select_delivery_details: "Select Delivery Route Details",
    select_pune_loc: "Select Delivery Location (from stored files)",
    select_date: "Choose Delivery Date",
    select_slot: "Choose Delivery Time Range Slot",
    coupon_discount: "Have an enterprise promo code?",
    apply: "Apply",
    coupon_applied: "Enterprise discount coupon applied successfully!",
    delivery_charge_lbl: "Local Logistics Charge",
    discount_applied: "Promo Code Savings",
    subtotal_lbl: "Products Subtotal",
    grand_total_lbl: "Grand Settled Price",
    select_pay_method: "Secure Digital Gateway Selection",
    cod_lbl: "Cash on Delivery (COD)",
    upi_lbl: "Instant UPI (PhonePe / GPay Sim)",
    card_lbl: "Credit / Debit Cards Secure checkout",
    nb_lbl: "Net Banking (SBI / HDFC Gateway)",
    pay_and_order: "Pay & Book Premium Shipment",
    processing_pay: "Initiating Secure Bank Sandbox Transaction...",
    ordered_placed_msg: "Order Placed Successfully!",

    // Addresses modal
    delivery_map_sim: "Ingali Grid Map Route Simulator",
    select_map_info: "Click an Ingali geographical landmark area on the grid map to fetch coordinates immediately into input fields:",
    address_label: "Address Type Label (e.g. Home, Office, Temple)",
    full_address: "Exact Delivery Address Line & Landmark Details",
    input_pincode: "Pincode (Default: 411001)",
    save_address_cta: "Save Certified Location Route",
    label_home: "Home",
    label_office: "Office",

    // Multi-Language Switch labels
    toggle_lang: "Switch to Marathi (मराठी)",
    current_lang: "English"
  },
  mr: {
    // Portals Switcher
    console_active: "श्रीराम जल सिस्टम कन्सोल सक्रिय आहे",
    customer_storefront: "🏡 ग्राहक स्टोअरफ्रंट",
    live_admin: "⚙️ लाइव्ह ॲडमिन पॅनेल",
    blueprints: "📚 इंजिनियरिंग ब्ल्यूप्रिंट्स",

    // Brand and Headings
    brand_title: "SHRIRAM JAL",
    brand_tagline: "PURE WATER, PURE LIFE",
    pune_trusted: "आम्हालाच का निवडाल?",
    pune_trusted_sub: "RO + UV + Ozonized शुद्धीकरण केलेले पाणी",
    pune_premium_tag: "✨ इंगळीची प्रीमियम पाणी सेवा • मालक: रणजित मोरे",
    order_now_banner: "शुद्ध पाणी, जलद डिलिव्हरी तुमच्या दारात!",
    order_now_banner_desc: "थंड आणि नॉर्मल पाण्याचे कॅन आता एक क्लिकवर ऑर्डर करा.",
    quick_shortcuts: "तात्काळ डिलिव्हरी शॉर्टकट",
    explore_catalog: "उत्पादने पहा",
    how_it_works: "ऑर्डर कशी कराल?",
    water_can_normal_20l: "२० लिटर नॉर्मल कॅन",
    water_can_cold_20l: "२० लिटर चिल्ड कॅन",
    delivery_coverage: "सक्रिय कव्हरेज क्षेत्र: इंगळी आणि हातकणंगले परिसर",
    delivery_coverage_sub: "जैन बस्ती जवळ, इंगळी येथील मुख्य केंद्रावरून जलद सेवा पुरवली जाते:",
    feedback_residents: "ग्राहकांचे अभिप्राय",
    support_hotline: "📞 मदत हेल्पलाईन: +९१ ९३०७३ १९९२९ / +९१ ८८५६० ४५९४५",
    support_email: "info@shriramjal.com",
    owner_info: "मालक: रणजित मोरे",
    operational_office: "कार्यालय पत्ता",
    registered_hub: "नोंदणीकृत: जैन बस्ती जवळ, इंगळी, हातकणंगले, कोल्हापूर, भारत",
    all_rights_reserved: "© 2024 Shriram Jal. All Rights Reserved.",

    // General navigation
    home: "मुख्यपृष्ठ",
    order_cans: "उत्पादने",
    subscription: "सबस्क्रिप्शन",
    about_us: "आमच्याबद्दल",
    contact_us: "संपर्क साधा",
    track_orders: "ऑर्डर ट्रॅक करा",
    cart: "कार्ट",
    my_orders_footer: "माझ्या ऑर्डर्स",
    address_records_footer: "पत्ता रेकॉर्ड्स",

    // Auth screen & login / signup
    sign_in: "लॉगिन / नोंदणी",
    sign_up: "नोंदणी करा",
    log_out: "लॉगआउट",
    welcome: "स्वागत आहे",
    login_required: "प्रवेश मर्यादित",
    login_subtext: "पाण्याच्या ऑर्डर्स देण्यासाठी आणि थेट डिलिव्हरी ट्रॅक करण्यासाठी कृपया लॉगिन करा किंवा खाते तयार करा.",
    enter_email: "ईमेल पत्ता किंवा युझरनेम",
    enter_password: "पासवर्ड",
    enter_name: "पूर्ण नाव",
    enter_phone: "फोन नंबर",
    no_account: "खाते नाही का?",
    already_member: "पूर्वीपासून नोंदणी केली आहे का?",
    sign_up_cta: "नवीन खाते तयार करा",
    sign_in_cta: "सुरक्षित लॉगिन करा",
    admin_restriction_title: "प्रशासकीय टर्मिनल लॉक आहे",
    admin_restriction_sub: "इंगळी प्रशासकीय पॅनेलसाठी सत्यापित पर्यवेक्षक प्रवेश आवश्यक आहे. सामान्य वापरकर्त्यांना येथे प्रवेश नाही.",
    admin_login_cta: "ॲडमिन लॉगिन सत्यापित करा",
    authenticated_as: "सत्यापित युझर",
    logged_in_as: "लॉगइन केलेले खाते",

    // Catalog & filter
    product_catalog: "ताजेतवाने उत्पादने कॅटलॉग",
    all_types: "सर्व पाणी प्रकार",
    normal_temp: "नॉर्मल तापमानाचे पाणी",
    cold_temp: "थंड पाणी (चिल्ड)",
    all_sizes: "सर्व आकार / क्षमता",
    select_size: "आकार निवडा",
    available_stock: "शिल्लक साठा",
    out_of_stock: "साठा संपला",
    add_to_cart: "कार्तमध्ये जोडा",
    buy_now: "तात्काळ ऑर्डर करा",
    quantity: "प्रमाण (नग)",
    fast_delivery: "⚡ ३ तासात जलद डिलिव्हरी",

    // Cart and order checkout
    cart_summary: "तुमचे कार्ट",
    cart_empty: "तुमचे वॉटर कार्ट पूर्णपणे रिकामे आहे.",
    cart_empty_sub: "ऑर्डर सुरू करण्यासाठी आमचे प्रीमियम नॉर्मल आणि चिल्ड पाण्याचे कॅन्स पहा.",
    start_shopping: "पाणी उत्पादने पहा",
    checkout_process: "सुरक्षित चेकआउट प्रक्रिया",
    select_delivery_details: "डिव्हरीचा तपशील निवडा",
    select_pune_loc: "डिलिव्हरीचा पत्ता निवडा (साठवलेल्या पत्त्यांमधून)",
    select_date: "डिलिव्हरीची तारीख निवडा",
    select_slot: "डिलिव्हरीची वेळ निवडा",
    coupon_discount: "तुमच्याकडे प्रोमो कोड आहे का?",
    apply: "लागू करा",
    coupon_applied: "प्रोमो कोड यशस्वीरित्या लागू झाला आहे!",
    delivery_charge_lbl: "स्थानिक डिलिव्हरी शुल्क",
    discount_applied: "प्रोमो कोड सवलत",
    subtotal_lbl: "उत्पादनांची रक्कम",
    grand_total_lbl: "एकूण देय रक्कम",
    select_pay_method: "सुरक्षित डिजिटल पेमेंट पद्धत",
    cod_lbl: "डिलिव्हरीवर पैसे द्या (COD)",
    upi_lbl: "तात्काळ UPI पेमेंट (PhonePe / GPay)",
    card_lbl: "क्रेडिट / डेबिट कार्ड सुरक्षित चेकआउट",
    nb_lbl: "नेट बँकिंग (SBI / HDFC गेटवे)",
    pay_and_order: "पैसे द्या आणि पाणी बुक करा",
    processing_pay: "पेमेंट गेटवे सुरक्षित व्यवहार सुरू करत आहे...",
    ordered_placed_msg: "ऑर्डर यशस्वीरित्या पूर्ण झाली!",

    // Addresses modal
    delivery_map_sim: "इंगळी नकाशा मार्ग जनरेटर",
    select_map_info: "इनपुट फील्डमध्ये तात्काळ कोऑर्डिनेट्स मिळवण्यासाठी नकाशावरील इंगळी क्षेत्रावर क्लिक करा:",
    address_label: "पत्ता प्रकार लेबल (उदा. घर, कार्यालय, मंदिर)",
    full_address: "पत्ता आणि जवळची खूण (Landmark) तपशील",
    input_pincode: "पिनकोड (डिफॉल्ट: ४११००१)",
    save_address_cta: "पत्ता मार्ग सुरक्षित करा",
    label_home: "घर",
    label_office: "कार्यालय",

    // Multi-Language Switch labels
    toggle_lang: "Switch to English",
    current_lang: "मराठी"
  }
};

export const getTranslation = (key: string, lang: Language): string => {
  return TRANSLATIONSObj[lang]?.[key] || TRANSLATIONSObj['en']?.[key] || key;
};
